name: CI

on:
  push: 
    branches:
      - main
  pull_request: 
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno task test
      - run: deno fmt --check
      - run: deno lint
